#!/usr/bin/env bash
# stage_erda.sh — assemble the ERDA data package for Fernandez-Guerra et al. 2025
#
# Contains ONLY the data files read by the analysis scripts.
# Code (scripts/, supp-tab-v2/) lives on GitHub.
#
# A user will:
#   1. Clone the GitHub repo  →  gets analysis/scripts/, libs/, etc.
#   2. Download + extract this ERDA package
#   3. Softlink or copy data/ and results/ into analysis/
#
# Usage:
#   bash .scripts/stage_erda.sh [DEST]
#
# Default DEST: /maps/projects/caeg/people/kbd606/projects-old/erda-2025-kapk-microbial
#
# Estimated output size: ~1.8 GB  (data/ ~1.4 GB + results/ ~400 MB)

set -euo pipefail

REPO="/maps/projects/fernandezguerra/apps/repos/2025-kapk-microbial"
ANALYSIS="${REPO}/analysis"
DEST="${1:-/maps/projects/caeg/people/kbd606/projects-old/erda-2025-kapk-microbial}"
DATA_SRC="/maps/projects/caeg/people/kbd606/projects-old/2025-kapk-microbial-submission/data"
PAPER_RUN="/maps/projects/caeg/people/kbd606/scratch/kapk-assm/amber/paper_run"

echo "=== Staging ERDA data package ==="
echo "Source:  ${ANALYSIS}"
echo "Dest:    ${DEST}"
echo ""

mkdir -p "${DEST}"

# ---------------------------------------------------------------------------
# 1. data/  — full copy, symlinks materialised so package is self-contained
#    data/benchmarks and data/sims come from kapk-microbial-analysis (old repo)
#    data/viral (VirSorter2 scores) could not be located; only used by assembly-overview.R
# ---------------------------------------------------------------------------
echo "→ data/"
rsync -a --copy-links "${DATA_SRC}/" "${DEST}/data/"

# ---------------------------------------------------------------------------
# 2. results/controls/
# ---------------------------------------------------------------------------
echo "→ results/controls/"
mkdir -p "${DEST}/results"
rsync -a "${ANALYSIS}/results/controls/" "${DEST}/results/controls/"

# ---------------------------------------------------------------------------
# 3. results/damage/  — only files read by scripts
# ---------------------------------------------------------------------------
echo "→ results/damage/"
mkdir -p "${DEST}/results/damage"
for f in \
    dmg_thresholds.tsv \
    tp-mdmg.weight-1.local.10M.agg.nobloom.csv.gz \
    tp-mdmg.weight-1.local.10M.nobloom.csv.gz \
    tp-mdmg.weight-1.local.10M.agg.csv.gz \
    tp-mdmg.weight-1.local.10M.agg.sp.csv.gz; do
    src="${ANALYSIS}/results/damage/${f}"
    [ -f "$src" ] && rsync -a "$src" "${DEST}/results/damage/" || echo "  MISSING: $f"
done

# ---------------------------------------------------------------------------
# 4. results/taxonomy/  — only files read by scripts
# ---------------------------------------------------------------------------
echo "→ results/taxonomy/"
mkdir -p "${DEST}/results/taxonomy"
for f in \
    kapk_ps_ba_gm.rds \
    tp-mapping-filtered.nocontam.10M.agg.nobloom.tax.tsv.gz \
    tp-mapping-filtered.nocontam.10M.nobloom.tax.tsv.gz \
    tp-mapping-filtered.nocontam.tax.tsv.gz \
    tp-mapping-filtered.nocontam.10M.tax.tsv.gz \
    tp-mapping-filtered.nocontam.10M.agg.tax.tsv.gz; do
    src="${ANALYSIS}/results/taxonomy/${f}"
    [ -f "$src" ] && rsync -a "$src" "${DEST}/results/taxonomy/" || echo "  MISSING: $f"
done
# anvio/ subfolder (read by 07a)
[ -d "${ANALYSIS}/results/taxonomy/anvio" ] && \
    rsync -a "${ANALYSIS}/results/taxonomy/anvio/" "${DEST}/results/taxonomy/anvio/"

# ---------------------------------------------------------------------------
# 5. results/sourcetracker/  — mixing proportions + feature tables (read by 05)
# ---------------------------------------------------------------------------
echo "→ results/sourcetracker/"
mkdir -p "${DEST}/results/sourcetracker"
# Aggregate outputs
for f in \
    mixing_proportions.txt \
    mixing_proportions_stds.txt \
    st-biome-gm.map \
    st-biome-class-gm.biom \
    decOM_output-dmg-k29.csv; do
    src="${ANALYSIS}/results/sourcetracker/${f}"
    [ -f "$src" ] && rsync -a "$src" "${DEST}/results/sourcetracker/" || echo "  MISSING: $f"
done
# Per-sample feature tables (read by 05 via list.files)
find "${ANALYSIS}/results/sourcetracker" -maxdepth 1 -name "*.feature_table.txt" | \
    while read -r f; do rsync -a "$f" "${DEST}/results/sourcetracker/"; done

# ---------------------------------------------------------------------------
# 6. results/mag_quality/  — TSV generated by generate_mag_table.R
# ---------------------------------------------------------------------------
echo "→ results/mag_quality/"
rsync -a "${ANALYSIS}/results/mag_quality/" "${DEST}/results/mag_quality/"

# ---------------------------------------------------------------------------
# 7. results/functional_agp/  — aggregates + per-sample slim files only
#    Excluded: emi.protein.tsv (~12 GB), emi.reads.tsv (~14 GB), blast8 (~6.5 GB)
# ---------------------------------------------------------------------------
echo "→ results/functional_agp/ (lean)"
FA="${ANALYSIS}/results/functional_agp"
DF="${DEST}/results/functional_agp"
mkdir -p "$DF"

# Top-level aggregate files (read by 14-summary-tables.R)
for f in kegg_module_damage.tsv cazy_family_damage.tsv; do
    [ -f "${FA}/${f}" ] && rsync -a "${FA}/${f}" "${DF}/" || echo "  MISSING: ${f}"
done

# KEGG per-sample slim files (read by 07a--agp-functional.R)
echo "  → functional_agp/kegg/ (slim per-sample)"
for sample_dir in "${FA}/kegg"/*/; do
    [ -d "$sample_dir" ] || continue
    sample=$(basename "$sample_dir")
    mkdir -p "${DF}/kegg/${sample}"
    for f in anvio_modules.txt emi.protein.slim.tsv.gz emi.functional.tsv pathway_damage_stats.tsv; do
        src="${sample_dir}${f}"
        [ -f "$src" ] && rsync -a "$src" "${DF}/kegg/${sample}/" || true
    done
done

# CAZy per-sample slim files (read by 07a--agp-functional.R)
echo "  → functional_agp/cazy/ (slim per-sample)"
for sample_dir in "${FA}/cazy"/*/; do
    [ -d "$sample_dir" ] || continue
    sample=$(basename "$sample_dir")
    mkdir -p "${DF}/cazy/${sample}"
    for f in cazy_emi.functional.tsv cazy_damage.slim.tsv.gz; do
        src="${sample_dir}${f}"
        [ -f "$src" ] && rsync -a "$src" "${DF}/cazy/${sample}/" || true
    done
done

# Viral per-sample (read by 14-summary-tables.R via list.files)
echo "  → functional_agp/viral/ (functional TSV only)"
for sample_dir in "${FA}/viral"/*/; do
    [ -d "$sample_dir" ] || continue
    sample=$(basename "$sample_dir")
    mkdir -p "${DF}/viral/${sample}"
    src="${sample_dir}viral_emi.functional.tsv"
    [ -f "$src" ] && rsync -a "$src" "${DF}/viral/${sample}/" || true
done

# ---------------------------------------------------------------------------
# 8. results/virome_agp/  — per-sample functional TSV (read by 08d--virome-figures.R)
# ---------------------------------------------------------------------------
echo "→ results/virome_agp/ (lean)"
VA="${ANALYSIS}/results/virome_agp"
DV="${DEST}/results/virome_agp"
mkdir -p "$DV"

for sample_dir in "${VA}/functional"/*/; do
    [ -d "$sample_dir" ] || continue
    sample=$(basename "$sample_dir")
    mkdir -p "${DV}/functional/${sample}"
    src="${sample_dir}viral_emi.functional.tsv"
    [ -f "$src" ] && rsync -a "$src" "${DV}/functional/${sample}/" || true
done

# ---------------------------------------------------------------------------
# 9. manuscript/tables/  — pre-computed inputs for 14-summary-tables.R
#    (sourced from kapk-microbial-analysis/manuscript/tables/)
# ---------------------------------------------------------------------------
echo "→ manuscript/tables/"
MT_SRC="${ANALYSIS}/manuscript/tables"
MT_DEST="${DEST}/manuscript/tables"
mkdir -p "$MT_DEST"
for f in \
    kapk_reextractions-cdata.tsv \
    kapk_reextractions-taxonomy.tsv \
    briggs_rl-percid.tsv.gz \
    briggs_rl-ancient-isrecal1.tsv.gz \
    bowtie2-benchmarks.tsv \
    saturation.tsv \
    simulations-detection-stats-composition.tsv \
    simulations-abundance-mdae.tsv \
    simulations-damage-mdae.tsv; do
    src="${MT_SRC}/${f}"
    [ -f "$src" ] && rsync -a "$src" "${MT_DEST}/" || echo "  MISSING: manuscript/tables/${f}"
done

# ---------------------------------------------------------------------------
# 10. data/methanoflorens/  — AMBER paper_run outputs for 15--methanoflorens-stasis.R
#     These are input data (BEAST2 trees/logs, phylogenomics, deconvolution),
#     placed under data/ since they are read by the analysis script, not generated by it.
# ---------------------------------------------------------------------------
echo "→ data/methanoflorens/ (AMBER paper_run outputs)"
DM="${DEST}/data/methanoflorens"
mkdir -p "$DM"

# Deconvolution outputs
mkdir -p "${DM}/deconvolve"
for f in read_length_histogram.tsv smiley_data.tsv damage_model.tsv; do
    src="${PAPER_RUN}/deconvolve/${f}"
    [ -f "$src" ] && rsync -a "$src" "${DM}/deconvolve/" || echo "  MISSING: deconvolve/${f}"
done
[ -d "${PAPER_RUN}/s17_assembly/deconvolve" ] && {
    mkdir -p "${DM}/s17_assembly/deconvolve"
    for f in read_length_histogram.tsv smiley_data.tsv; do
        src="${PAPER_RUN}/s17_assembly/deconvolve/${f}"
        [ -f "$src" ] && rsync -a "$src" "${DM}/s17_assembly/deconvolve/" || echo "  MISSING: s17_assembly/deconvolve/${f}"
    done
}

# Methanoflorens metadata (reference genome metadata for tree annotation)
src="/maps/projects/caeg/people/kbd606/scratch/kapk-assm/tmp/deconv_bin28/phylogenomics/Methanoflorentales_update_2026-02-09/_Methanoflorentales_update_METADAT_2026-02-09.txt"
[ -f "$src" ] && rsync -a "$src" "${DM}/methanoflorens_metadata.txt" || echo "  MISSING: methanoflorens_metadata.txt"

# FastANI + phylogenomics
for f in \
    fastani/deconvolved_vs_refs.tsv \
    phylogenomics_79taxa_bak/08_trees/codon12_ml_tree.treefile \
    phylogenomics_79taxa_bak/11_focal_snps/focal_pairwise_snp_counts.tsv \
    phylogenomics_79taxa_bak/11_focal_snps/focal_pairwise_ani.tsv; do
    src="${PAPER_RUN}/${f}"
    dst_dir="${DM}/$(dirname "$f")"
    mkdir -p "$dst_dir"
    [ -f "$src" ] && rsync -a "$src" "${dst_dir}/" || echo "  MISSING: ${f}"
done

# BEAST2 outputs (logs + MCC trees)
for beast_dir in \
    beast2_nodec/tipdating \
    beast2_nodec/ucld_tipdating \
    beast2_nodec/2clock_stasis \
    beast2_nodec/freedate_rep3 \
    beast2_nodec/freedate_rep4; do
    src_dir="${PAPER_RUN}/${beast_dir}"
    [ -d "$src_dir" ] || continue
    dst_dir="${DM}/${beast_dir}"
    mkdir -p "$dst_dir"
    for f in codon_tipdating_mcc.tree codon_tipdating.log codon_2clock_stasis_nodec.log codon_freedate_nodec.log; do
        [ -f "${src_dir}/${f}" ] && rsync -a "${src_dir}/${f}" "${dst_dir}/" || true
    done
done
# Path sampling outputs (ps_*/)
for ps_dir in "${PAPER_RUN}/beast2_nodec"/ps_*/; do
    [ -d "$ps_dir" ] || continue
    ps_name=$(basename "$ps_dir")
    mkdir -p "${DM}/beast2_nodec/${ps_name}"
    [ -f "${ps_dir}/beast_ps.out" ] && rsync -a "${ps_dir}/beast_ps.out" "${DM}/beast2_nodec/${ps_name}/" || true
done

# ---------------------------------------------------------------------------
# 12. results/dart_benchmark/  — benchmark data + pre-generated figures
# ---------------------------------------------------------------------------
echo "→ results/dart_benchmark/"
rsync -a "${ANALYSIS}/results/dart_benchmark/" "${DEST}/results/dart_benchmark/"

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo ""
echo "=== Done ==="
du -sh "${DEST}/data"               2>/dev/null | awk '{print "  data/               " $1}'
du -sh "${DEST}/results"            2>/dev/null | awk '{print "  results/            " $1}'
du -sh "${DEST}/manuscript"         2>/dev/null | awk '{print "  manuscript/         " $1}'
echo ""
du -sh "${DEST}"                    2>/dev/null | awk '{print "  TOTAL               " $1}'
echo ""
echo "ERDA data package staged at: ${DEST}"
