
virus_structural_protein <- c(
    "terminase large subunit",
    "major head protein",
    "virion structural protein",
    "portal protein",
    "tail protein",
    "tail length tape measure protein",
    "baseplate protein",
    "minor head protein",
    "terminase small subunit",
    "head morphogenesis",
    "head maturation protease",
    "head-tail connector protein",
    "baseplate assembly protein",
    "tail fiber protein",
    "minor tail protein",
    "head protein",
    "tail sheath",
    "tail terminator",
    "head closure",
    "tail assembly chaperone",
    "head scaffolding protein",
    "lytic tail protein",
    "major tail protein",
    "head-tail adaptor",
    "head closure Hc1",
    "CTXphi Zot-like toxin",
    "tail collar fiber protein",
    "DarB-like antirestriction",
    "short tail fiber protein",
    "assembly (protein IV of M13)",
    "tail protein and host specificity",
    "distal tail protein",
    "baseplate hub",
    "terminase",
    "tail assembly protein",
    "head-tail adaptor Ad1",
    "tail completion",
    "Satellite tobacco necrosis virus coat protein",
    "lytic tail fiber protein",
    "minor head protein and DNA pilot",
    "tail tube protein",
    "morphogenesis (protein I of M13)",
    "collagen like minor tail"
)

dna_rna_transactions_processing <- c(
    "transcriptional regulator",
    "integrase",
    "HNH endonuclease",
    "exonuclease",
    "DNA primase",
    "clamp loader of DNA polymerase",
    "DNA binding protein",
    "Avd protein of DGR",
    "endonuclease",
    "transcriptional repressor",
    "transcriptional regulator WhiB-like",
    "polymerase",
    "excisionase",
    "HTH DNA binding protein",
    "exonuclease V",
    "transposase",
    "single strand DNA binding protein",
    "DNA polymerase",
    "ParB-like partition protein",
    "replication initiation protein",
    "DNA repair protein",
    "RecE-like recombination exonuclease",
    "DNA invertase",
    "RNA polymerase beta subunit",
    "UmuD-like protein",
    "RecT-like ssDNA annealing protein",
    "DnaC-like helicase loader",
    "DNA topoisomerase II",
    "anti-repressor Ant",
    "recombinase",
    "Arc-like repressor",
    "Geminivirus Rep catalytic domain",
    "CsrA-like regulator",
    "primosomal protein",
    "rolling circle DNA replication initiation",
    "helicase",
    "partition protein ATPase",
    "anti-repressor",
    "DNA ligase",
    "helicase loader",
    "NinG/ Rap DNA junction specific endonuclease",
    "DNA replication initiation",
    "replisome organizer",
    "replication protein",
    "anti-termination protein Q-like",
    "single strand annealing protein"
)


lysis <- c(
    "endolysin",
    "peptidase",
    "holin",
    "Rz-like spanin"
)

ta_rm_systems <- c(
    "DNA methyltransferase",
    "antitoxin from a toxin-antitoxin system",
    "RelE-like toxin",
    "toxin",
    "methyltransferase"
)

amg_and_other <- c(
    "glycoside hydrolase",
    "acetyltransferase",
    "cation efflux protein",
    "hydrolase",
    "radical SAM domain-containing protein",
    "ATPase",
    "kinase",
    "phosphoadenosine phosphosulfate reductase",
    "MazF-like growth inhibitor",
    "thioredoxin domain",
    "phosphoheptose isomerase",
    "nucleotide kinase",
    "sigma factor",
    "GtrB glycosyltransferase for O-antigen conversion",
    "esterase",
    "serine-threonine kinase",
    "signal peptide motif",
    "ferredoxin",
    "translational regulator",
    "deoxyribonucleoside 5' monophosphate phosphatase",
    "UDP-glucose dehydrogenase",
    "esterase/lipase",
    "nitroreductase",
    "hemolysin",
    "sulfatase-modifying factor enzyme",
    "radical SAM domain protein",
    "sporulation stage III protein D",
    "glutamine amidotransferase"
)

vir_phyla <- c(
    "p__Uroviricota",
    "p__Cressdnaviricota",
    "p__Hofneiviricota",
    "p__Phixviricota",
    "p__Nucleocytoviricota",
    "Methanogenic viruses"
)
