__default__:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 1
  partition: debug
  cpus_per_task: 1

initial_stats:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 16
  partition: debug

rename_reads:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 32
  partition: debug

norm_reads:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 32
  partition: debug

derep_reads:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 16
  partition: debug

extension_stats:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 16
  partition: debug

extend_reads:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 16
  partition: debug

assembly_penguin_extended:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 32
  partition: debug
assembly_plass_extended:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 32
  partition: debug

assembly_megahit_extended:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 32
  partition: debug

mmseqs_profile_to:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 32
  partition: debug

mmseqs_busco_viridiplantae:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 32
  partition: debug

mmseqs_busco_fungi:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 32
  partition: debug

mmseqs_traits:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 32
  partition: debug

read_gene_prediction_fgs:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 16
  partition: debug

assembly_plass:
  nodes: 9
  ntasks: 9
  ntasks_per_node: 1
  cpus_per_task: 32
  partition: debug

extract_matched_reads:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 8
  partition: debug

kraken2_refinement:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 32
  partition: debug

combine_assemblies:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 32
  partition: debug

refine_assemblies:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 32
  partition: debug

map_reads_assembly:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 16
  partition: debug

pydamage:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 32
  partition: debug

contig_taxonomy:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 32
  partition: debug

gene_renaming_prodigal:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 16
  partition: debug

eggnog_mapper_genes:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 32
  partition: debug

gene_abundance_estimation:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 8
  partition: debug

mmseqs_profile_permafrost:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 32
  partition: debug

kraken2_profiling_coarse:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 16
  partition: debug

kraken2_profiling_hires:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 16
  partition: debug

kaiju_profiling:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 32
  partition: debug

motus_profiling:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 16
  partition: debug

woltka_profiling:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 16
  partition: debug

woltka_profiling_summary:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 4
  partition: debug

woltka_metaDMG:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 16
  partition: debug

resistome:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 16
  partition: debug

reads_bgc:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 16
  partition: debug

map_smags:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 32
  partition: debug

get_organelles:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 32
  partition: debug

assembly_refine_stats:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 8
  partition: debug

get_viruses:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 32
  partition: debug

vamb_concatenate:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 32
  partition: debug

vamb_mapping:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 32
  partition: debug

vamb_binning:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 8
  partition: gpu

vamb_checkm:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 32
  partition: debug

vamb_anvio_create_contigsdb:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 32
  partition: debug

anvio_create_contigsdb:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 32
  partition: debug

anvio_profile:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 32
  partition: debug

anvio_get_kofam:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 32
  partition: debug

vamb_anvio_profile:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 32
  partition: debug

vamb_anvio_import_collection:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 32
  partition: debug

anvio_create_gene_catalog_nondamaged:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 32
  partition: debug

anvio_create_gene_catalog_damaged:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 32
  partition: debug

anvio_estimate_metabolism:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 8
  partition: debug

mmseqs_profile_kegg_reads:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 32
  partition: debug

kraken2_profiling_get_euk_reads:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 8
  partition: debug

anvio_profile_kegg_reads:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 4
  partition: debug