# Basic config File
# Where is the workflow
wdir: "/maps/projects/lundbeck/people/kbd606/repos/aMAW-taxonomy"
# Where is the data
sdir: "/maps/projects/lundbeck/people/kbd606/projects/kapk/data/all"
# Where is the output
rdir: "/maps/projects/lundbeck/people/kbd606/projects/kapk/results"

tmp: "/dev/shm/tmp"
#sample_file_read: "/vol/cloud/geogenetics/mediterranean/analysis/assets/med-samples-raw-filt-reads.tsv"
sample_file_read: "/maps/projects/lundbeck/people/kbd606/projects/kapk/assets/samples.tsv"

###############################################################################
#
# Common config values
#
###############################################################################
#Add binary paths
mmseqs_bin: /vol/cloud/geogenetics/opt/bin/mmseqs
xfilter_bin: xFilter
seqkit_bin: seqkit
rename_bin: rename.sh
vsearch_bin: vsearch
tadpole_bin: tadpole.sh
loglog_bin: loglog.sh
bowtie2_bin: bowtie2
samtools_bin: samtools
filter_bam_bin: filterBAM

# threads
seqkit_threads: 16
extract_threads: 8
norm_threads: 32
read_rename_threads: 16
read_extension_threads: 8
read_derep_threads: 8
mmseqs2_threads: 32
anvio_threads: 4
resistome_reads_threads: 32

# Rename reads
rename_reads: False
read_minlen: 30
rename_parms: "addunderscore=f overwrite=t"

# Read dereplication
derep_reads: True
derep_parms: "--strand both --sizeout --fastaout -"

# Read extension
extend_reads: True
loglog_bits: 16
loglog_hashes: 3
loglog_table_cap: 0.5
loglog_memory: "300G"
loglog_seed: 1234
tadpole_mode: "extend"
tadpole_length: 100
tadpole_memory: "300G"
tadpole_k: 17
minprobprefilter: f
trimends: 9
prefilter: 0
# set to 0 for automatic, with a value run will be deterministic (in bytes)
maxmem: "214748364800"
ibb: f
ecc: t
ecco: f
conservative: t

# Xfilter & MMseqs2 parameters
# Kegg reads mapping
annotation_source: "KEGGgenes"
kegg_db: "/vol/cloud/geogenetics/DBs/kegg/20220228/genes/mmseqs2/kegg_genes-i0.9-c0.8"
kegg_gene_list: "/vol/cloud/geogenetics/DBs/kegg/20220228/genes/mmseqs2/ko_genes.list"
mmseqs_kegg_parms: "--comp-bias-corr 0 --mask 0 -e 1e-5 --exact-kmer-matching 1 --sub-mat PAM30.out -s 3 -k 6 --spaced-kmer-pattern 11011101 --min-length 15 --format-mode 2 -c 0.8 --cov-mode 2 --min-seq-id 0.6"
xfilter_parms: "-n 25 -b 20 -e 1e-5 --breadth-expected-ratio 0.6"
anvi_estimate_extra_parms: "--user-modules /maps/projects/lundbeck/scratch/antonio/projects/taxDB/20220926/TaxDB_v3/user_supplied/woodcroft2018/kegg-modules"

# dbCAN read mapping
dbcan_db:
dbcan_gene_list:
mmseqs_dbcan_parms: "--comp-bias-corr 0 --mask 0 -e 1e-5 --exact-kmer-matching 1 --sub-mat PAM30.out -s 3 -k 6 --spaced-kmer-pattern 11011101 --min-length 15 --format-mode 2 -c 0.8 --cov-mode 2 --min-seq-id 0.6"

# RESISTOME
run_resistome_reads: True
megares_db_bw: "/vol/cloud/geogenetics/DBs/megares/2.0.0/megares_modified_database_v2.00"
resistome_thres: 0.8
resistome_bowtie2_params: "--very-sensitive --no-unal"
resistome_filter_nreads: 5
filter_sort_mem: 1G

# Get damaged reads
dread_bin: dReads
dread_filter: '{ "Bayesian_D_max": 0.1, "Bayesian_z": 2.5 }'
mdmg_weight: [1]
get_dmg_reads: True
